// Map.hpp
#pragma once

#include <vector>
#include <string>
#include <cstdint>
#include <allegro5/allegro.h>
#include <allegro5/allegro_image.h>
#include "Engine/AudioHelper.hpp"
#include "Engine/IScene.hpp"
#include "Engine/Tile.hpp"
#include "Engine/Sprite.hpp"
#include "Player/Player.hpp"

// 基本點座標結構
struct Point {
    int x;
    int y;
};

namespace Engine {
    class Group;
    class Image;
    class Label;
    class Sprite;
    class Tile;
}   // namespace Engine

enum class BlockType : uint16_t {
    FLOOR,
    //GRASS1,
    //GRASS2,
    //GRASSSAND,
    WALL,
    //GRASSSAND,
    TREE1,
    GROUND1,
    GROUND2,
    GROUND3,
    GROUND4,
    GROUND5,
    GROUND6,
    GROUND7,
    GROUND8,
    GROUND9,
    GROUND10,
    GROUND11,
    GROUND12,
    GROUND13,
    GROUND14,
    GROUND15,
    GROUND16,
    GROUND17,
    GROUND18,
    GROUND19,
    GROUND20,
    GROUND21,
    GROUND22,
    GROUND23,
    GROUND24,
    GROUND25,
    GROUND26,
    GROUND27,
    GROUND28,
    GROUND29,
    GROUND30,
    GROUND31,
    GROUND32,
    GROUND33,
    GROUND35,
    GROUND34,
    GROUND36,
    GROUND37,
    GROUND38,
    GROUND39,
    GROUND40,
    GROUND41,
    GROUND42,

    TENNIS1,
    TENNIS2,
    TENNIS3,
    TENNIS4,
    TENNIS5,
    TENNIS6,
    TENNIS7,
    TENNIS8,
    TENNIS9,
    TENNIS10,
    TENNIS11,
    TENNIS12,
    TENNIS13,
    TENNIS14,
    TENNIS15,
    TENNIS16,
    TENNIS17,
    TENNIS18,
    TENNIS19,
    TENNIS20,
    TENNIS21,
    TENNIS22,
    TENNIS23,
    TENNIS24,
    TENNIS25,
    TENNIS26,
    TENNIS27,
    TENNIS28,
    TENNIS29,
    TENNIS30,
    TENNIS31,
    TENNIS32,
    TENNIS33,
    TENNIS34,
    TENNIS35,
    TENNIS36,
    TENNIS37,
    TENNIS38,
    TENNIS39,
    TENNIS40,
    TENNIS41,
    TENNIS42,
    
    CSBUILDING1,
    CSBUILDING2,
    CSBUILDING3,
    CSBUILDING4,
    CSBUILDING5,
    CSBUILDING6,
    CSBUILDING7,
    CSBUILDING8,
    CSBUILDING9,
    CSBUILDING10,
    CSBUILDING11,
    CSBUILDING12,
    CSBUILDING13,
    CSBUILDING14,
    CSBUILDING15,
    CSBUILDING16,
    CSBUILDING17,
    CSBUILDING18,
    CSBUILDING19,
    CSBUILDING20,
    CSBUILDING21,
    CSBUILDING22,
    CSBUILDING23,
    CSBUILDING24,
    CSBUILDING25,
    CSBUILDING26,
    CSBUILDING27,
    CSBUILDING28,
    CSBUILDING29,
    CSBUILDING30,
    CSBUILDING31,
    CSBUILDING32,
    CSBUILDING33,
    CSBUILDING34,
    CSBUILDING35,
    CSBUILDING36,
    CSBUILDING37,
    CSBUILDING38,
    CSBUILDING39,
    CSBUILDING40,
    CSBUILDING41,
    CSBUILDING42,
    CSBUILDING43,
    CSBUILDING44,
    CSBUILDING45,
    CSBUILDING46,
    CSBUILDING47,
    CSBUILDING48,
    CSBUILDING49,
    CSBUILDING50,

    LAKE1,
    LAKE2,
    LAKE3,
    LAKE4,
    LAKE5,
    LAKE6,
    LAKE7,
    LAKE8,
    LAKE9,
    LAKE10,
    LAKE11,
    LAKE12,
    LAKE13,
    LAKE14,
    LAKE15,
    LAKE16,
    LAKE17,
    LAKE18,
    LAKE19,
    LAKE20,
    LAKE21,
    LAKE22,
    LAKE23,
    LAKE24,
    LAKE25,

    QINLAKE1,
    QINLAKE2,
    QINLAKE3,
    QINLAKE4,
    QINLAKE5,
    QINLAKE6,
    QINLAKE7,
    QINLAKE8,
    QINLAKE9,
    QINLAKE10,
    QINLAKE11,
    QINLAKE12,
    QINLAKE13,
    QINLAKE14,
    QINLAKE15,
    QINLAKE16,
    QINLAKE17,
    QINLAKE18,
    QINLAKE19,
    QINLAKE20,
    QINLAKE21,
    QINLAKE22,
    QINLAKE23,
    QINLAKE24,
    QINLAKE25,
    QINLAKE26,
    QINLAKE27,
    QINLAKE28,
    QINLAKE29,
    QINLAKE30,
    QINLAKE31,
    QINLAKE32,
    QINLAKE33,
    QINLAKE34,
    QINLAKE35,
    QINLAKE36,
    QINLAKE37,
    QINLAKE38,
    QINLAKE39,
    QINLAKE40,

    PARKING1,
    PARKING2,
    PARKING3,
    PARKING4,
    PARKING5,
    PARKING6,
    PARKING7,
    PARKING8,
    PARKING9,
    PARKING10,
    PARKING11,
    PARKING12,
    PARKING13,
    PARKING14,
    PARKING15,
    PARKING16,
    PARKING17,
    PARKING18,

    CODE1,
    CODE2,
    CODE3,
    CODE4,
    CODE5,
    CODE6,
    CODE7,
    CODE8,
    CODE9,
    CODE10,
    CODE11,
    CODE12,
    CODE13,
    CODE14,
    CODE15,
    CODE16,
    CODE17,
    CODE18,
    CODE19,
    CODE20,
    CODE21,
    CODE22,
    CODE23,
    CODE24,
    CODE25,
    CODE26,
    CODE27,
    CODE28,
    CODE29,
    CODE30,

    POOL1,
    POOL2,
    POOL3,
    POOL4,
    POOL5,
    POOL6,
    POOL7,
    POOL8,
    POOL9,
    POOL10,
    POOL11,
    POOL12,
    POOL13,
    POOL14,
    POOL15,
    POOL16,
    POOL17,
    POOL18,
    POOL19,
    POOL20,
    POOL21,
    POOL22,
    POOL23,
    POOL24,
    POOL25,

    HAM1,
    HAM2,
    HAM3,
    HAM4,
    HAM5,
    HAM6,
    HAM7,
    HAM8,
    HAM9,
    HAM10,
    HAM11,
    HAM12,
    HAM13,
    HAM14,
    HAM15,
    HAM16,
    HAM17,
    HAM18,
    HAM19,
    HAM20,
    HAM21,
    HAM22,
    HAM23,
    HAM24,
    HAM25,
    HAM26,
    HAM27,
    HAM28,
    HAM29,
    HAM30,
    HAM31,
    HAM32,
    HAM33,
    HAM34,
    HAM35,
    HAM36,

    CLUB1,
    CLUB2,
    CLUB3,
    CLUB4,
    CLUB5,
    CLUB6,
    CLUB7,
    CLUB8,
    CLUB9,
    CLUB10,
    CLUB11,
    CLUB12,
    CLUB13,
    CLUB14,
    CLUB15,
    CLUB16,
    CLUB17,
    CLUB18,
    CLUB19,
    CLUB20,
    CLUB21,
    CLUB22,
    CLUB23,
    CLUB24,
    CLUB25,
    CLUB26,
    CLUB27,
    CLUB28,
    CLUB29,
    CLUB30,
    CLUB31,
    CLUB32,
    CLUB33,
    CLUB34,
    CLUB35,
    CLUB36,

    REST1,
    REST2,
    REST3,
    REST4,
    REST5,
    REST6,
    REST7,
    REST8,
    REST9,
    REST0,
    REST10,
    REST11,
    REST12,

    SHOP1,
    SHOP2,
    SHOP3,
    SHOP4,
    SHOP5,
    SHOP6,
    SHOP7,
    SHOP8,
    SHOP9,

    LIBRARY1,
    LIBRARY2,
    LIBRARY3,
    LIBRARY4,
    LIBRARY5,
    LIBRARY6,
    LIBRARY7,
    LIBRARY8,
    LIBRARY9,
    LIBRARY10,
    LIBRARY11,
    LIBRARY12,
    LIBRARY13,
    LIBRARY14,
    LIBRARY15,
    LIBRARY16,
    LIBRARY17,
    LIBRARY18,
    LIBRARY19,
    LIBRARY20,
    LIBRARY21,
    LIBRARY22,
    LIBRARY23,
    LIBRARY24,
    LIBRARY25,
    LIBRARY26,
    LIBRARY27,
    LIBRARY28,
    LIBRARY29,
    LIBRARY30,
    LIBRARY31,
    LIBRARY32,
    LIBRARY33,
    LIBRARY34,
    LIBRARY35,
    LIBRARY36,
    LIBRARY37,
    LIBRARY38,
    LIBRARY39,
    LIBRARY40,
    LIBRARY41,
    LIBRARY42,
    LIBRARY43,
    LIBRARY44,
    LIBRARY45,
    LIBRARY46,
    LIBRARY47,
    LIBRARY48,

    CASTLE1,
    CASTLE2,
    CASTLE3,
    CASTLE4,
    CASTLE5,
    CASTLE6,
    CASTLE7,
    CASTLE8,
    CASTLE9,
    CASTLE10,
    CASTLE11,
    CASTLE12,
    CASTLE13,
    CASTLE14,
    CASTLE15,
    CASTLE16,
    CASTLE17,
    CASTLE18,
    CASTLE19,
    CASTLE20,
    CASTLE21,
    CASTLE22,
    CASTLE23,
    CASTLE24,
    CASTLE25,
    CASTLE26,
    CASTLE27,
    CASTLE28,
    CASTLE29,
    CASTLE30,
    CASTLE31,
    CASTLE32,
    CASTLE33,
    CASTLE34,
    CASTLE35,
    CASTLE36,
    CASTLE37,
    CASTLE38,
    CASTLE39,
    CASTLE40,
    CASTLE41,
    CASTLE42,
    CASTLE43,
    CASTLE44,
    CASTLE45,
    CASTLE46,
    CASTLE47,
    CASTLE48,

    COFFEE1,
    COFFEE2,
    COFFEE3,
    COFFEE4,
    COFFEE5,
    COFFEE6,
    COFFEE7,
    COFFEE8,
    COFFEE9,
    COFFEE10,
    COFFEE11,
    COFFEE12,
    COFFEE13,
    COFFEE14,
    COFFEE15,
    COFFEE16,
    COFFEE17,
    COFFEE18,
    COFFEE19,
    COFFEE20,
    COFFEE21,
    COFFEE22,
    COFFEE23,
    COFFEE24,

    GRASS1,
    GRASS2,
    GRASS3,
    GRASS4,
    GRASS5,
    GRASS6,
    GRASS7,
    GRASS8,
    GRASS9,
    GRASS10,
    GRASS11,
    GRASS12,
    GRASS13,
    GRASS14,
    GRASS15,
    GRASS16,
    GRASS17,
    GRASS18,
    GRASS19,
    GRASS20,
    GRASS21,
    GRASS22,
    GRASS23,
    GRASS24,

    ROCKROAD,
    HOUSE,
    FLOWER1,
    FLOWER2,
    //DOOR_CLOSE,
    //HOLE,
    COIN,
    NOTHING
};

enum class CoinStatus : uint8_t {
    APPEAR,
    DISAPPEARING,
    DISAPPEAR
};

class Map  : public Engine::IScene {
protected:
    PlayScene *getPlayScene();
    PlayScene *scene;
public:
    int tileSize = 128;
    //Map(const std::string& filepath);
    Map();
    //~Map();
    void cleanup();
    // 不允許拷貝，避免資源錯亂
    Map(const Map&) = delete;
    Map& operator=(const Map&) = delete;

    //void draw(const Point& cameraPos);
    //void update(const Point& playerPos, int& totalCoins);
    void draw();
    void update(float deltaTime);

    bool isWalkable(BlockType block) const;
    void Initialize() override;
    void Terminate()override;
    Engine::Point WorldToTile(const Engine::Point& pos);
    BlockType GetBlock(const Engine::Point& tilePos);

    void loadMapFromFile(const std::string& filepath);
    const std::vector<std::vector<BlockType>>& GetGrid() const;

    int GetWidth() const;
    int GetHeight() const;

private:
    int rows;
    int cols;

    //bool hasTriggeredQuiz = false;
    std::set<std::pair<int, int>> triggeredQuizzes;
    bool WaitToChangeScene = false;
    float quizTriggerTimer = 0.0f;

    Tile* tileSet[600];

    // 使用vector管理地圖格子與硬幣狀態
    std::vector<std::vector<BlockType>> mapGrid;
    std::vector<std::vector<CoinStatus>> coinStatus;
    std::vector<std::vector<BlockType>> tiles;
    ALLEGRO_BITMAP* tileset = nullptr;
    ALLEGRO_BITMAP* coinSprites = nullptr;
    ALLEGRO_SAMPLE_ID coinAudio;

    Point spawnPoint;
    std::vector<Point> enemySpawns;
    std::vector<char> enemyCodes;

    // 硬幣動畫相關
    std::vector<std::vector<int>> coinAnimationFrame;
    int coinAnimationTimer = 0;

    
    

};
